spring:
  application:
    name: employee-management
  datasource:
    url: jdbc:postgresql://localhost:5431/management-employee
    username: postgres
    password: 3+0M1606Pc_4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8018
