spring:
  application:
    name: employee-management
  datasource:
    url: jdbc:postgresql://103.90.227.237:5431/management-employee
    username: postgres
    password: 3+0M1606Pc_4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000       # 1h in millisecond

server:
  port: 8018
